"""Score the Crossref journal and proceedings sweep, the Zenodo conference records and the JIM and
SBCM proceedings (by their English text) against the joined archives.

Each article (title and, where Crossref has it, abstract) is scored by its mean cosine
similarity to its ten nearest archive entries, leaving out the entry for the article itself.
The check: the off-NIME archive already holds a curated set of Computer Music Journal articles,
so their percentile among all CMJ articles shows whether the score separates NIME-related work.
The score is the contrast between closeness to the archives and closeness to the rest of the
sweep; a candidate needs at least the curated median contrast and the curated lower-quartile closeness. Writes
output/candidates_journals.tsv, output/candidates_journals.bib and data/journal_candidates.json.
"""
import json
import re
from collections import Counter
from pathlib import Path

import numpy as np
from sklearn.feature_extraction.text import ENGLISH_STOP_WORDS, TfidfVectorizer

from parse_refs import title_key

HERE = Path(__file__).resolve().parent.parent
K = 10
REL_CQ, REL_NQ = 75, 50


def write_bib(path, items, collection=None):
    path.parent.mkdir(exist_ok=True)
    with open(path, "w") as f:
        if collection is None:
            f.write("% Journal and proceedings papers that score as NIME-related and are in neither archive.\n"
                    "% Generated by analysis/tools/score_journals.py. Not curated.\n\n")
        keys = set()
        for it in items:
            sur = re.sub(r"[^a-z]", "", (it["authors"][0].split()[-1].lower() if it["authors"] and it["authors"][0].split() else "anon"))
            key = f"{sur}{it['year']}{re.sub(r'[^a-z]', '', it['title'].lower())[:12]}"
            if collection:
                key = f"{collection.lower()}:{key}"
            while key in keys:
                key += "b"
            keys.add(key)
            kind = "article" if it["type"] == "journal-article" else "inproceedings"
            fields = [("author", " and ".join(it["authors"])), ("title", it["title"]),
                      ("journal" if kind == "article" else "booktitle", it["container"]), ("year", it["year"]),
                      ("volume", it["volume"]), ("number", it["issue"]),
                      ("pages", (it["pages"] or "").replace("-", "--") or None), ("doi", it["doi"]),
                      ("url", it.get("url") if not it["doi"] else None),
                      ("collection", collection),
                      ("note", "; ".join(x for x in [f"Original title: {it['title_orig']}" if it.get("title_orig") and it["title_orig"] != it["title"] else "",
                                                    f"Selected by similarity to the archives (score {it['score']})" if collection else ""] if x) or None)]
            f.write(f"@{kind}{{{key},\n" + ",\n".join(f"  {k} = {{{re.sub(r'[{}]', '', str(v))}}}" for k, v in fields if v)
                    + "\n}\n\n")


def main():
    corpus = json.loads((HERE / "data" / "corpus.json").read_text())
    items = json.loads((HERE / "data" / "journals.json").read_text())
    # the background is the seven journals only; proceedings and other sources are scored against it
    from crossref import JOURNALS
    for it in items:
        it["background"] = it["source"] in JOURNALS
    for extra in ("zenodo.json", "nonenglish.json", "sbcm_volumes.json", "proceedings_extra.json"):
        f = HERE / "data" / extra
        if f.exists():
            items += [dict(it, background=False) for it in json.loads(f.read_text())]
    for it in items:
        it["title"] = re.sub(r"\s+", " ", re.sub(r"<[^>]+>", "", it["title"])).strip()
        it["authors"] = [re.sub(r"\s+", " ", a).strip() for a in it["authors"]]
    items = [it for it in items if it["year"] and not re.match(r"(front matter|back matter|editor|announcement|"
                                                                r"letters?\b|about the|contributors|index|books? received|"
                                                                r"news|products of interest|erratum|correction)", it["title"], re.I)]
    # research articles only: reviews of records, books, products and concerts are short, and
    # their short titles score high on any word they share with the archives
    def pages(it):
        m = re.match(r"(\d+)\D+(\d+)$", it.get("pages") or "")
        return int(m.group(2)) - int(m.group(1)) + 1 if m else None
    items = [it for it in items if len(re.findall(r"[A-Za-z]{2,}", it["title"])) >= 4
             and (pages(it) is None or pages(it) >= 4)]
    by_doi = {r["doi"]: r["id"] for r in corpus if r["doi"]}
    by_key = {title_key(r["title"]): r["id"] for r in corpus if title_key(r["title"])}
    for it in items:
        it["in_corpus"] = by_doi.get(it["doi"].lower()) or by_key.get(title_key(it["title"]))

    vec = TfidfVectorizer(stop_words=list(ENGLISH_STOP_WORDS), min_df=3, max_df=0.4, sublinear_tf=True,
                          token_pattern=r"(?u)\b[a-zA-Z][a-zA-Z\-]{2,}\b")
    C = vec.fit_transform([f"{r['title']}. {r['keywords']}. {r['abstract']}" for r in corpus])
    L = vec.transform([f"{it['title']}. {it['abstract']}" for it in items])
    S = (L @ C.T).toarray()
    col = {r["id"]: j for j, r in enumerate(corpus)}
    for i, it in enumerate(items):
        if it["in_corpus"]:
            S[i, col[it["in_corpus"]]] = 0
    # contrast: closeness to the archives minus closeness to the rest of the sweep, so that a
    # generic title near everything scores low
    # the background is the journal sweep alone, so that adding a large source (SMC on Zenodo)
    # does not move every score, nor penalise that source for having many similar papers
    bg = np.array([i for i, it in enumerate(items) if it["background"]])
    B = (L @ L[bg].T).toarray()
    B[bg, np.arange(len(bg))] = 0
    near = np.sort(S, axis=1)[:, -K:].mean(1)
    score = near - np.sort(B, axis=1)[:, -K:].mean(1)
    nn = S.argmax(1)
    for it, s, a, n in zip(items, score, near, nn):
        it["score"] = round(float(s), 4)
        it["near"] = float(a)
        it["nearest"] = corpus[n]["title"]

    cmj = [it for it in items if it["source"] == "Computer Music Journal"]
    cur = [it for it in cmj if it["in_corpus"]]
    allc = np.array([it["score"] for it in cmj])
    pct = [float((allc < it["score"]).mean() * 100) for it in cur]
    check = {"cmj_articles": len(cmj), "curated_cmj": len(cur),
             "curated_median_percentile": round(float(np.median(pct)), 1),
             "curated_share_in_top_quarter": round(float(np.mean([p >= 75 for p in pct]) * 100), 1)}
    # a candidate must be both close to the archives (at least the curated lower quartile) and
    # closer to them than to the sweep (at least the curated median contrast)
    thresh = float(np.median([it["score"] for it in cur]))
    near_min = float(np.percentile([it["near"] for it in cur], 25))
    cands = sorted([it for it in items if not it["in_corpus"] and it["score"] >= thresh and it["near"] >= near_min],
                   key=lambda it: -it["score"])

    # the Related dataset: a strict tier of the candidates, at the curated upper quartile of contrast
    # and median of closeness (few off-topic titles in a sampled reading, against many at the looser
    # candidate thresholds), excluding what
    # Cited or Theses already hold and keeping one copy of a title found in two venues
    rel_c = float(np.percentile([it["score"] for it in cur], REL_CQ))
    rel_n = float(np.percentile([it["near"] for it in cur], REL_NQ))
    taken = set()
    for name in ("Cited", "Theses"):
        f = HERE.parent / "bibs" / name / f"{name.lower()}.bib"
        if f.exists():
            for m in re.finditer(r"(?:doi|title) = \{([^}]*)\}", f.read_text()):
                taken.add(m.group(1).lower() if "/" in m.group(1) else title_key(m.group(1)))
    related, seen_t = [], set()
    for it in cands:
        k = title_key(it["title"])
        if it["score"] < rel_c or it["near"] < rel_n or it["doi"].lower() in taken or k in taken or k in seen_t:
            continue
        seen_t.add(k)
        related.append(it)
    write_bib(HERE.parent / "bibs" / "Related" / "related.bib", related, collection="Related")
    with open(HERE / "output" / "candidates_journals.tsv", "w") as f:
        f.write("score\tsource\tyear\ttitle\tauthors\tdoi\tnearest_archive_entry\n")
        for it in cands:
            f.write("\t".join(str(x) for x in [it["score"], it["source"], it["year"], it["title"],
                                                 "; ".join(it["authors"][:6]), it["doi"], it["nearest"]]) + "\n")
    write_bib(HERE / "output" / "candidates_journals.bib", cands)
    summary_related = {"related": len(related), "related_contrast_min": round(rel_c, 4), "related_near_min": round(rel_n, 4)}
    summary = {**summary_related, "check": check, "threshold": round(thresh, 4), "near_min": round(near_min, 4), "items": len(items),
               "by_source": dict(Counter(it["source"] for it in items)),
               "in_corpus": sum(1 for it in items if it["in_corpus"]),
               "candidates": dict(Counter(it["source"] for it in cands)), "n_candidates": len(cands),
               "with_abstract": sum(1 for it in items if it["abstract"]),
               "top": [{k: it[k] for k in ["score", "source", "year", "title", "authors", "doi", "nearest"]} for it in cands[:300]]}
    (HERE / "data" / "journal_candidates.json").write_text(json.dumps(summary, ensure_ascii=False, indent=1))
    print(json.dumps({k: v for k, v in summary.items() if k != "top"}, indent=1))
    for it in cands[:25]:
        print(it["score"], it["source"][:20], it["year"], "|", it["title"][:80])


if __name__ == "__main__":
    main()
